{
 "title": "01 - Confluent Cloud - Overview",
 "tags": [ "confluent_cloud" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {
     "query": "label_values(confluent_kafka_server_partition_count,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "bytes in / minute",
   "type": "stat",
   "description": "https://api.telemetry.confluent.cloud/docs/descriptors/datasets/cloud",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_server_received_bytes{job=~\"${environment}\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "bytes out / minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_server_sent_bytes{job=~\"${environment}\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total Topic Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_server_retained_bytes{job=~\"${environment}\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total Topics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (confluent_kafka_server_retained_bytes{job=~\"${environment}\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Cluster Partition Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_kafka_server_partition_count{job=~\"${environment}\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Schema Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_schema_registry_schema_count{job=~\"${environment}\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Bytes In / Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_server_received_bytes{job=~\"${environment}\"}) by (job, kafka_id)",
     "legendFormat": "{{kafka_id}} ({{job}})"
    }
   ]
  },
  {
   "title": "Bytes Out / Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_server_sent_bytes{job=~\"${environment}\"}) by (job, kafka_id)",
     "legendFormat": "{{kafka_id}} ({{job}})"
    }
   ]
  },
  {
   "title": "Messages In / Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_server_received_records{job=~\"${environment}\"}) by (job, kafka_id)",
     "legendFormat": "{{kafka_id}} ({{job}})"
    }
   ]
  },
  {
   "title": "Messages Out - Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_server_sent_records{job=~\"${environment}\"}) by (job, kafka_id)",
     "legendFormat": "{{kafka_id}} ({{job}})"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_server_active_connection_count{job=~\"${environment}\"}) by (job, kafka_id)",
     "legendFormat": "{{kafka_id}} ({{job}})"
    }
   ]
  },
  {
   "title": "Successful Authentications / Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_server_successful_authentication_count{job=~\"${environment}\"}) by (job, kafka_id)",
     "legendFormat": "{{kafka_id}} ({{job}})"
    }
   ]
  },
  {
   "title": "Total Requests / Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_server_request_count{job=~\"${environment}\"}) by (job, kafka_id)",
     "legendFormat": "{{kafka_id}} ({{job}})"
    }
   ]
  },
  {
   "title": "Client Software Versions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(confluent_kafka_server_connection_info{client_software_name=~\".+\", client_id=~\".+\"} > 0) by (client_software_name, client_software_version)",
     "legendFormat": "{{client_software_name}} ({{client_software_version}})"
    }
   ]
  },
  {
   "title": "Cluster Load",
   "type": "timeseries",
   "description": "Dedicated Clusters Only",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_server_cluster_load_percent{job=~\"$environment\"}) by (job, kafka_id)",
     "legendFormat": "{{kafka_id}} ({{job}})"
    }
   ]
  }
 ]
}