{
 "title": "02 - Confluent Cloud - Topics",
 "tags": [ "confluent_cloud" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {
     "query": "label_values(confluent_kafka_server_partition_count,job)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(confluent_kafka_server_partition_count{job=\"$environment\"},kafka_id)"
    }
   },
   { "name": "topic", "label": "Topic Regexp", "query": ".*" },
   {
    "name": "hide_internal",
    "label": "exclude '_confluent'",
    "query": "yes : _confluent.* , no : __________"
   }
  ]
 },
 "panels": [
  {
   "title": "bytes in / minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_server_received_bytes{job=~\"${environment}\", kafka_id=~\"${cluster}\", topic=~\"${topic}\", topic!~\"$hide_internal\"})"
    }
   ]
  },
  {
   "title": "bytes out / minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_server_sent_bytes{job=~\"${environment}\", kafka_id=~\"${cluster}\", topic=~\"${topic}\", topic!~\"$hide_internal\"})"
    }
   ]
  },
  {
   "title": "Bytes In / Minute",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(25, sum (confluent_kafka_server_received_bytes{job=~\"${environment}\", kafka_id=~\"${cluster}\", topic=~\"${topic}\", topic!~\"$hide_internal\"}) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out / Minute",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(25, sum (confluent_kafka_server_sent_bytes{job=~\"${environment}\", kafka_id=~\"${cluster}\", topic=~\"${topic}\", topic!~\"$hide_internal\"}) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages In / Minute",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(15, sum (confluent_kafka_server_received_records{job=~\"${environment}\", kafka_id=~\"${cluster}\", topic=~\"${topic}.*\", topic!~\"$hide_internal\"}) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages Out / Minute",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(15, sum (confluent_kafka_server_sent_records{job=~\"${environment}\", kafka_id=~\"${cluster}\", topic=~\"${topic}.*\", topic!~\"$hide_internal\"}) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Retention Bytes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(15, sum (confluent_kafka_server_retained_bytes{job=~\"${environment}\", kafka_id=~\"${cluster}\", topic=~\"${topic}\", topic!~\"$hide_internal\"}) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "topics matching regular expression = ${topic}",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": " (confluent_kafka_server_retained_bytes{job=~\"${environment}\", kafka_id=~\"${cluster}\", kafka_id=~\"${cluster}\", topic=~\"${topic}\", topic!~\"$hide_internal\"}) ",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}