{
 "title": "04 - Confluent Cloud - Principal",
 "tags": [ "confluent_cloud" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {
     "query": "label_values(confluent_kafka_server_partition_count,job)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(confluent_kafka_server_partition_count{job=\"$environment\"},kafka_id)"
    }
   },
   {
    "name": "principal",
    "query": {
     "query": "label_values(confluent_kafka_server_request_bytes{job=~\"$environment\", kafka_id=~\"$cluster\"},principal_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Bytes / minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_server_request_bytes{type=\"Produce\", job=~\"${environment}\", kafka_id=~\"${cluster}\", principal_id=~\"${principal}\"})"
    }
   ]
  },
  {
   "title": "Response Bytes / Minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_server_response_bytes{type=\"Fetch\", job=~\"${environment}\", kafka_id=~\"${cluster}\", principal_id=~\"${principal}\"}) "
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_server_active_connection_count{job=~\"${environment}\", kafka_id=~\"${cluster}\", principal_id=~\"${principal}\"})"
    }
   ]
  },
  {
   "title": "Request Bytes - ${principal}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_server_request_bytes{job=~\"${environment}\", kafka_id=~\"${cluster}\", principal_id=~\"${principal}\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Response Bytes - ${principal}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_server_response_bytes{job=~\"${environment}\", kafka_id=~\"${cluster}\", principal_id=~\"${principal}\"}) ",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Request Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_server_request_bytes{type=\"Produce\", job=~\"${environment}\", kafka_id=~\"${cluster}\", principal_id=~\"${principal}\"}) by (principal_id, type)",
     "legendFormat": "{{principal_id}} ({{type}})"
    }
   ]
  },
  {
   "title": "Response Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_server_response_bytes{type=\"Fetch\", job=~\"${environment}\", kafka_id=~\"${cluster}\", principal_id=~\"${principal}\"}) by (principal_id)",
     "legendFormat": "{{principal_id}}"
    }
   ]
  },
  {
   "title": "Active Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_server_active_connection_count{job=~\"${environment}\", kafka_id=~\"${cluster}\", principal_id=~\"${principal}\"} > 0) by (principal_id)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Request Count / Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_server_request_count{job=~\"${environment}\", kafka_id=~\"${cluster}\", principal_id=~\"${principal}\"} > 0) by (principal_id, type)",
     "legendFormat": "{{principal_id}}  ({{type}})"
    }
   ]
  }
 ]
}