{
 "title": "05 - Confluent Cloud - Schema Registry",
 "tags": [ "confluent_cloud" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {
     "query": "label_values(confluent_kafka_schema_registry_request_count,job)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(confluent_kafka_schema_registry_request_count{job=\"$environment\"},schema_registry_id)"
    }
   },
   {
    "name": "principal",
    "query": {
     "query": "label_values(confluent_kafka_schema_registry_request_count{job=~\"$environment\", schema_registry_id=~\"$cluster\"},principal_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Rate - ${principal}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (rate(confluent_kafka_schema_registry_request_count{job=~\"${environment}\", schema_registry_id=~\"${cluster}\", principal_id=~\"${principal}\"}[$__rate_interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Request Count - ${principal}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_schema_registry_request_count{job=~\"${environment}\", schema_registry_id=~\"${cluster}\", principal_id=~\"${principal}\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Schema Create Rate - ${principal}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_schema_registry_schema_operations_count{method=\"CREATE\", status=\"SUCCESS\", job=~\"${environment}\", schema_registry_id=~\"${cluster}\", principal_id=~\"${principal}\"})",
     "legendFormat": "{{principal_id}}"
    }
   ]
  },
  {
   "title": "Schema Read Rate - ${principal}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_schema_registry_schema_operations_count{method=\"READ\", status=\"SUCCESS\", job=~\"${environment}\", schema_registry_id=~\"${cluster}\", principal_id=~\"${principal}\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Schema Delete Rate - ${principal}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (confluent_kafka_schema_registry_schema_operations_count{method=\"DELETE\", status=\"SUCCESS\", job=~\"${environment}\", schema_registry_id=~\"${cluster}\", principal_id=~\"${principal}\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}