{
 "title": "06 - Confluent Cloud - Connect",
 "tags": [ "confluent_cloud" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {
     "query": "label_values(confluent_kafka_schema_registry_request_count,job)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(confluent_kafka_connect_connector_status{job=\"$environment\"},connector_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connectors",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "confluent_kafka_connect_connector_status{job=~\"${environment}\", connector_id=~\"${cluster}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "confluent_kafka_connect_connector_task_status{job=~\"${environment}\", connector_id=~\"${cluster}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Records Sent Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "msgs" } },
   "targets": [
    {
     "expr": "sum by (connector_id) (confluent_kafka_connect_sent_records{job=~\"${environment}\", connector_id=~\"${cluster}\"})",
     "legendFormat": "{{conector_id}}"
    }
   ]
  },
  {
   "title": "Records Sent Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "msgs" } },
   "targets": [
    {
     "expr": "sum by (connector_id) (confluent_kafka_connect_sent_records{job=~\"${environment}\", connector_id=~\"${cluster}\"})",
     "legendFormat": "{{connector_id}}"
    }
   ]
  }
 ]
}